### ISSUE TITLE
Changing the locked key door player sound from DSOOF to DSNOWAY

### ISSUE THREAD

**Issue by BigStronk64** [MrAlaux/Nugget-Doom#100]
There are some mods that use DSOOF and replaces it with other non human sound effects such as boots hitting the floor. This sound strange when using a locked door as it plays that sound instead of the Doomguy oof
There is the additional benefit being that it makes more sense as DSNOWAY is used to signify that there is no way through the door without a key

**Comment by MrAlaux** [comment]
I can add this as an optional Doom Compat setting later.

**Comment by MrAlaux** [comment]
Done in https://github.com/MrAlaux/Nugget-Doom/commit/141adf44d49ca6e52efd3514e717ab04c2f4456b.
