### ISSUE TITLE
[Bug]  Enabling Voxels Disables Crosshair Lock On Target

### ISSUE THREAD

**Issue by CharlesLove** [MrAlaux/Nugget-Doom#104]
- Platform: Linux
- Version: 3.2.0 (corrected app-image)
- Problem:
    - When enabling voxel mode, the lock on feature for crosshairs no longer works. The target will change colors, but will no longer snap to the enemies on screen. This only effects wads actively using the voxel pack.

**Comment by MrAlaux** [comment]
Makes sense, because the code that snaps the crosshair is run within the sprite-drawing code to avoid having to recalculate the sprite's position on the screen. Woof should be affected too.
