### ISSUE TITLE
symbol lookup error

### ISSUE THREAD

**Issue by Blackfox-Thane** [MrAlaux/Nugget-Doom#106]
I tried to launch nugget doom, but this error happens

`symbol lookup error: /usr/lib/libjack.so.0: undefined symbol: pw_log_topic_register`

**Comment by MrAlaux** [comment]
I've absolutely no idea of what that means, but it looks like you're on an Unix-based system. Could you try the AppImage in [here](https://github.com/MrAlaux/Nugget-Doom/actions/runs/10190517913)?

**Comment by Blackfox-Thane** [comment]
Your link did the trick it runs now, thanks
