### ISSUE TITLE
Option for Quit Sound Effects

### ISSUE THREAD

**Issue by SilverSpireZ** [MrAlaux/Nugget-Doom#110]
Other source ports have an option to re-enable the quit sound effects present in vanilla Doom, but as far as I can tell, Woof and Nugget do not have this option. If possible, it would be nice to have this option available.

**Comment by MrAlaux** [comment]
For whatever reason, the quit sound is tied to ENDOOM: the sound plays only if the latter is going to be shown. I guess I can add a setting exclusively for toggling it.
