### ISSUE TITLE
Cannot load DOOM + DOOM II versions of Master Levels or No Rest for the Living

### ISSUE THREAD

**Issue by SilverSpireZ** [MrAlaux/Nugget-Doom#111]
I have tried loading the new versions of masterlevel.wad and nerve.wad from the Kex DOOM + DOOM II release, but neither work. The application doesn't open. I'm using these commands:

nugget-doom.exe -iwad doom2.wad -file masterlevels.wad
nugget-doom.exe -iwad doom2.wad -file nerve.wad

Seems this issue was fixed in Woof, so maybe a similar fix could be pushed here.

**Comment by MrAlaux** [comment]
> Seems this issue was fixed in Woof, so maybe a similar fix could be pushed here.

Indeed, but such fixes are usually only merged upon new Woof releases. Even then, I may have to investigate to find the commit fixed it.
