### ISSUE TITLE
[Feature] Enable/disable individual level stats

### ISSUE THREAD

**Issue by NoNamedNN** [MrAlaux/Nugget-Doom#113]
For example most people don't care about items count, and i only want to see enemy count.
So there should be a way to only show stats that the player wants to see.

**Comment by MrAlaux** [comment]
If I add this setting, I think it's reasonable to make it apply to just the normal Stats widget, whereas the automap's Stats widget would always show everything. What do you think?

**Comment by NoNamedNN** [comment]
Yes thats good

**Comment by seascape** [comment]
> If I add this setting, I think it's reasonable to make it apply to just the normal Stats widget, whereas the automap's Stats widget would always show everything. What do you think?

Since I only show stats in the automap, I'd personally like to be able to control which ones show in there. 😛

I'm a new Nugget user (LOVE IT!) and I'd actually wondered if disabling certain stats displaying was possible before determining that it was not.
