### ISSUE TITLE
[Feature] Add Crispy automap color preset from Woof

### ISSUE THREAD

**Issue by SilverSpireZ** [MrAlaux/Nugget-Doom#115]
Currently, Nugget Doom only has three automap presets: vanilla, boom, and zdoom. However, Woof also has a fourth preset for Crispy, set between Vanilla and Boom. It would be great to have this option present in Nugget as well.

**Comment by MrAlaux** [comment]
Again: when a new Woof release comes around, Nugget shall inherit its changes.
