### ISSUE TITLE
[Feature] Zdoom style centered message for weapon select

### ISSUE THREAD

**Issue by RotKingJoey** [MrAlaux/Nugget-Doom#116]
While I know there's an option to better highlight the currently selected weapon on the status bar, I tend to use the scroll wheel a lot for weapon switching. Its unclear sometimes which weapon slot is currently highlighted until after the switch action has completed. It would be super helpful if there was either a message or weapon pickup icon similar to the Doom + Doom 2 re-release that clearly shows you which weapon is currently selected.

**Comment by MrAlaux** [comment]
To be clear: the highlight feature first checks for a _pending_ weapon (i.e. the weapon you want to switch to) to highlight, and if there isn't one, it highlights the current weapon.

**Comment by MrAlaux** [comment]
@freakalope, the current master merged changes from Woof 15.0.0, which include a weapon carousel as seen in the KEX port:

![imagen](https://github.com/user-attachments/assets/18501623-f881-45be-ba3a-e74712952b46)

Now that we have this, I believe the ZDoom-style message is unnecessary. What do you think?

**Comment by MrAlaux** [comment]
I consider this resolved.
