### ISSUE TITLE
The latest release (and master branch) fails to build under Arch Linux

### ISSUE THREAD

**Issue by ghost** [MrAlaux/Nugget-Doom#12]
Full Terminal log:

  ~/projects:  wget https://github.com/MrAlaux/Nugget-Doom/archive/refs/tags/nugget-doom-1.10.0.tar.gz                           ✔                                                    
  ~/projects:  ex nugget-doom-1.10.0.tar.gz                                                                                                                                   ✔  4s  
  ~/projects:  cd Nugget-Doom-nugget-doom-1.10.0                                                                                                                   ✔                          
  ~/projects/Nugget-Doom-nugget-doom-1.10.0:  mkdir build && cd build                                                                               ✔                                        
  ~/projects/Nugget-Doom-nugget-doom-1.10.0/build:  cmake ..                                                                                                ✔                           
-- The C compiler identification is GNU 12.2.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Setting build type to 'RelWithDebInfo' as none was specified.
-- Looking for pow in m
-- Looking for pow in m - found
-- Looking for dirent.h
-- Looking for dirent.h - found
-- Looking for strsignal
-- Looking for strsignal - found
-- Looking for strcasecmp
-- Looking for strcasecmp - found
-- Looking for strncasecmp
-- Looking for strncasecmp - found
-- Found SDL2: /usr/include/SDL2 (found suitable version "2.24.0", minimum required is "2.0.7") 
-- Found SDL2_mixer: /usr/include/SDL2 (found suitable version "2.6.2", minimum required is "2.0.2") 
-- Found SDL2_net: /usr/include/SDL2 (found version "2.2.0") 
-- Found FluidSynth: /lib/libfluidsynth.so (found version "1.1.6") 
-- Found Python3: /usr/bin/python3.10 (found version "3.10.7") found components: Interpreter 
-- Performing Test CFLAG_Wdeclaration-after-statement
-- Performing Test CFLAG_Wdeclaration-after-statement - Success
-- Performing Test CFLAG_Werror_implicit-function-declaration
-- Performing Test CFLAG_Werror_implicit-function-declaration - Success
-- Performing Test CFLAG_Werror_incompatible-pointer-types
-- Performing Test CFLAG_Werror_incompatible-pointer-types - Success
-- Performing Test CFLAG_Werror_int-conversion
-- Performing Test CFLAG_Werror_int-conversion - Success
-- Performing Test CFLAG_Wformat_2
-- Performing Test CFLAG_Wformat_2 - Success
-- Performing Test CFLAG_Wnull-dereference
-- Performing Test CFLAG_Wnull-dereference - Success
-- Performing Test CFLAG_Wredundant-decls
-- Performing Test CFLAG_Wredundant-decls - Success
-- Performing Test CFLAG_Wrestrict
-- Performing Test CFLAG_Wrestrict - Success
-- Performing Test CFLAG_Wall
-- Performing Test CFLAG_Wall - Success
-- Configuring done
-- Generating done
-- Build files have been written to: /home/unyx/projects/Nugget-Doom-nugget-doom-1.10.0/build

 ~/projects/Nugget-Doom-nugget-doom-1.10.0/build:  make                                                                                                        2 ✘ 19s                          
[  1%] Building C object opl/CMakeFiles/opl.dir/opl.c.o
[  1%] Building C object opl/CMakeFiles/opl.dir/opl_queue.c.o
[  2%] Building C object opl/CMakeFiles/opl.dir/opl_sdl.c.o
[  3%] Building C object opl/CMakeFiles/opl.dir/opl3.c.o
[  3%] Linking C static library libopl.a
[  3%] Built target opl
[  3%] Building C object textscreen/CMakeFiles/textscreen.dir/txt_button.c.o
[  4%] Building C object textscreen/CMakeFiles/textscreen.dir/txt_checkbox.c.o
[  5%] Building C object textscreen/CMakeFiles/textscreen.dir/txt_desktop.c.o
[  5%] Building C object textscreen/CMakeFiles/textscreen.dir/txt_dropdown.c.o
[  6%] Building C object textscreen/CMakeFiles/textscreen.dir/txt_gui.c.o
[  7%] Building C object textscreen/CMakeFiles/textscreen.dir/txt_io.c.o
[  7%] Building C object textscreen/CMakeFiles/textscreen.dir/txt_inputbox.c.o
[  8%] Building C object textscreen/CMakeFiles/textscreen.dir/txt_fileselect.c.o
[  9%] Building C object textscreen/CMakeFiles/textscreen.dir/txt_label.c.o
[  9%] Building C object textscreen/CMakeFiles/textscreen.dir/txt_separator.c.o
[ 10%] Building C object textscreen/CMakeFiles/textscreen.dir/txt_scrollpane.c.o
[ 11%] Building C object textscreen/CMakeFiles/textscreen.dir/txt_strut.c.o
[ 11%] Building C object textscreen/CMakeFiles/textscreen.dir/txt_table.c.o
[ 12%] Building C object textscreen/CMakeFiles/textscreen.dir/txt_widget.c.o
[ 13%] Building C object textscreen/CMakeFiles/textscreen.dir/txt_window_action.c.o
[ 13%] Building C object textscreen/CMakeFiles/textscreen.dir/txt_window.c.o
[ 14%] Building C object textscreen/CMakeFiles/textscreen.dir/txt_sdl.c.o
[ 15%] Building C object textscreen/CMakeFiles/textscreen.dir/txt_utf8.c.o
[ 16%] Linking C static library libtextscreen.a
[ 16%] Built target textscreen
[ 17%] Building C object src/CMakeFiles/nugget-doom.dir/am_map.c.o
[ 18%] Building C object src/CMakeFiles/nugget-doom.dir/d_deh.c.o
[ 18%] Building C object src/CMakeFiles/nugget-doom.dir/d_items.c.o
[ 19%] Building C object src/CMakeFiles/nugget-doom.dir/d_iwad.c.o
[ 20%] Building C object src/CMakeFiles/nugget-doom.dir/d_main.c.o
[ 20%] Building C object src/CMakeFiles/nugget-doom.dir/d_loop.c.o
[ 21%] Building C object src/CMakeFiles/nugget-doom.dir/d_net.c.o
[ 22%] Building C object src/CMakeFiles/nugget-doom.dir/d_quit.c.o
[ 22%] Building C object src/CMakeFiles/nugget-doom.dir/doomdef.c.o
[ 23%] Building C object src/CMakeFiles/nugget-doom.dir/doomstat.c.o
[ 25%] Building C object src/CMakeFiles/nugget-doom.dir/dsdhacked.c.o
[ 25%] Building C object src/CMakeFiles/nugget-doom.dir/dstrings.c.o
[ 26%] Building C object src/CMakeFiles/nugget-doom.dir/f_finale.c.o
[ 27%] Building C object src/CMakeFiles/nugget-doom.dir/f_wipe.c.o
[ 27%] Building C object src/CMakeFiles/nugget-doom.dir/g_game.c.o
[ 28%] Building C object src/CMakeFiles/nugget-doom.dir/hu_lib.c.o
[ 29%] Building C object src/CMakeFiles/nugget-doom.dir/hu_stuff.c.o
[ 29%] Building C object src/CMakeFiles/nugget-doom.dir/i_endoom.c.o
[ 30%] Building C object src/CMakeFiles/nugget-doom.dir/i_flmusic.c.o
/home/unyx/projects/Nugget-Doom-nugget-doom-1.10.0/src/i_flmusic.c: In function ‘I_FL_InitMusic’:
/home/unyx/projects/Nugget-Doom-nugget-doom-1.10.0/src/i_flmusic.c:141:20: error: implicit declaration of function ‘new_fluid_defsfloader’; did you mean ‘new_fluid_player’? [-Werror=implicit-function-declaration]
  141 |         sfloader = new_fluid_defsfloader(settings);
      |                    ^~~~~~~~~~~~~~~~~~~~~
      |                    new_fluid_player
/home/unyx/projects/Nugget-Doom-nugget-doom-1.10.0/src/i_flmusic.c:141:18: error: assignment to ‘fluid_sfloader_t *’ {aka ‘struct _fluid_sfloader_t *’} from ‘int’ makes pointer from integer without a cast [-Werror=int-conversion]
  141 |         sfloader = new_fluid_defsfloader(settings);
      |                  ^
/home/unyx/projects/Nugget-Doom-nugget-doom-1.10.0/src/i_flmusic.c:142:9: error: implicit declaration of function ‘fluid_sfloader_set_callbacks’ [-Werror=implicit-function-declaration]
  142 |         fluid_sfloader_set_callbacks(sfloader, FL_sfopen, FL_sfread, FL_sfseek,
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: some warnings being treated as errors
make[2]: *** [src/CMakeFiles/nugget-doom.dir/build.make:328: src/CMakeFiles/nugget-doom.dir/i_flmusic.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:263: src/CMakeFiles/nugget-doom.dir/all] Error 2
make: *** [Makefile:156: all] Error 2
  ~/projects/Nugget-Doom-nugget-doom-1.10.0/build:

**Comment by MrAlaux** [comment]
Can you try building the latest master of Woof under the same system? `i_flmusic.c` is not a module I've edited, so if you're having an issue with it in Nugget Doom, I'm pretty sure that it should stem from Woof's codebase, where it should also be fixed.

**Comment by ghost** [comment]
Huh, that's kind of awkward. It fails to build too. Even tho I just built the latest version of woof yesterday.

**Comment by MrAlaux** [comment]
Awkward indeed. Could you please report the issue there too?

**Comment by ghost** [comment]
Yep, on my way already!

**Comment by ghost** [comment]
The issue was a old fluidsynth header left on my system. Deleting it resolved the issue, Thank you for the quick help and response!
