### ISSUE TITLE
Nugget doom doesn't work correctly

### ISSUE THREAD

**Issue by Someguyman** [MrAlaux/Nugget-Doom#125]
I've been having a major issue where the port straight up doesn't want to work proper. It shows up in my task manager when I look for it, but it doesn't show anything in the task bar or start the game properly. When I tried to use zdl it just gives me a "No such option "deathmath"" error. 
![image](https://github.com/user-attachments/assets/92e58075-c630-4f68-9b46-b609cb8c6212)

**Comment by MrAlaux** [comment]
It appears that ZDL is passing the `-deathmath` command-line parameter to Nugget, and since it (and surely every other port) doesn't recognize it, it throws this error and exits. Check your ZDL config.

To be clear: have you tried running Nugget directly by opening `nugget-doom.exe`?

**Comment by Someguyman** [comment]
> To be clear: have you tried running Nugget directly by opening `nugget-doom.exe`?

I already did that and it still doesn't work.

**Comment by MrAlaux** [comment]
Do the previous Nugget release (3.2.0) and the latest Woof release (14.5.0) work?

**Comment by MrAlaux** [comment]
@Someguyman, any updates?

**Comment by Someguyman** [comment]
> @Someguyman, any updates?

I'll try again with a fresh install

**Comment by Someguyman** [comment]
Yeah everything seems to work correctly now after having a fresh install. Still not sure how it stopped working last time but at least things are fine now. @MrAlaux.
