### ISSUE TITLE
[bug report] the "default crosshair color" does not work with "color by target health"

### ISSUE THREAD

**Issue by ghost** [MrAlaux/Nugget-Doom#14]
When Color by target health is selected the game disregards the default color setting and defaults to gray
![image](https://user-images.githubusercontent.com/68514898/194783527-5952f9db-92af-4910-a674-5018fb2bd5e5.png)
![image](https://user-images.githubusercontent.com/68514898/194783532-76c3e02e-448c-4c76-abba-41a790e81b10.png)
it does work as intended when the color by target health setting is turned off
![image](https://user-images.githubusercontent.com/68514898/194783538-d58334ac-d9cb-4df6-b51d-5322a44448d1.png)
![image](https://user-images.githubusercontent.com/68514898/194783544-aad820bb-eb79-4844-9df0-6d3c79eac345.png)

**Comment by MrAlaux** [comment]
This was intentional. By allowing the setting to take effect, the default color could be the same as one of the four colors used to indicate target health, which would probably be a bit confusing, especially if you can't actually see what the autoaim is targeting.

**Comment by ghost** [comment]
> This was intentional. By allowing the setting to take effect, the default color could be the same as one of the four colors used to indicate target health, which would probably be a bit confusing, especially if you can't actually see what the autoaim is targeting.

I play with a very strong blue light filter on most of the time so gray and yellow is basically the same color for me this is why I would want to change the crosshair color into blue/black
