### ISSUE TITLE
[Feature Request] Projected Crosshair from Crispy Doom and and enemy lock on with or without Projected Crosshair (like in dsda doom)

### ISSUE THREAD

**Issue by ghost** [MrAlaux/Nugget-Doom#15]
in Crispy doom the crosshair can be drawn projected out in to the game world itself
![image](https://user-images.githubusercontent.com/68514898/194783803-8557593e-6538-4810-bf58-ff18059786b4.png)
![image](https://user-images.githubusercontent.com/68514898/194783835-a721ace1-35e8-420f-b117-ef29454497e3.png)
the lock on:
![image](https://user-images.githubusercontent.com/68514898/194783914-36369974-039c-42b9-b48e-4cc50e14218b.png)
I know these two might be kind of an unpopular feature but I kind of like them, and would like to have them in this port!

**Comment by liPillON** [comment]
not a fan of the projected crosshair, but I strongly support the "lock on target" feature

**Comment by MrAlaux** [comment]
Target lock-on for the static crosshair has been implemented: e5ff76f1eb44e171edf3d059b1a6c5120947373c

**Comment by liPillON** [comment]
sweet!
tested it, works as expected..
thanks!

**Comment by ghost** [comment]
one small extension about the lock on feature: make an option for disabling the horizontal lock on for hit scan weapons because it's disorienting and inaccurate as f**k. Maybe a 15degree horizontal lock on indicator for the rocket launcher/plasma rifle to avoid self blow ups? 🤔

**Comment by MrAlaux** [comment]
Some clarification, just in case: The horizontal lock-on for hitscan weapons is there to represent the spread of said weapons, they have no horizontal autoaim. Projectile weapons do have autoaim, unless you disable it by means of the option to, well, toggle it.

**Comment by ghost** [comment]
I know, hitscan weapons got no horizontal autoaim, only projectile weapons that got a fixed 15degrees or so snappy lock.
What I want is the ability to turn off the visual only horizontal lock for hitscan weapons because it throws the aim off hard. 
I kind of forgot about that fact when I requested the feature. 
Meanwhile the option to have a visual representation for when the rocket launcher wants to troll you when a imp walks by the side of your screen would be great

This could be under like an option with the name like "Enemy Lock on strictly represents auto aim" or something that describes it better than i failed to

**Comment by MrAlaux** [comment]
Regarding the horizontal lock-on: 42a44c9606562bba4546b57c9ebdbe716570be46

**Comment by ghost** [comment]
welp, seems like now the vertical lock kind of breaks and fails to properly lock on the enemies, now it either displays too low when the enemy is above me and it displays too high when enemies are below me :/

**Comment by MrAlaux** [comment]
Oops, misclicked.

Anyways, can you show me screenshots of this new issue? I believe it shouldn't be happening, at least not because of the latest changes.

**Comment by MrAlaux** [comment]
Still awaiting for feedback on the allegedly-faulty vertical lock-on.

In the meanwhile, I've done something regarding horizontal autoaim: 307edb4bd1c40f1fdc0435ba536393d02f288981. It's probably not what you expected, but we can try it.

**Comment by liPillON** [comment]
Hi, I'm facing a crash on startup when the lock-on feature is enabled.
The error message is "I_SignalHandler: Exit on Floating-point error (Signal 8)"

I've been able to constantly reproduce this using a clean installation of the latest autobuild, no files in autoload and a config file with only the "hud_crosshair_on", "hud_crosshair_target" and "hud_crosshair_lockon" variables changed from their defaults.

It happens when warping to a map where the player starts directly facing a monster.
".\nugget-doom.com -iwad .\DOOM2.WAD -file .\ShowRoom2.wad -warp 88"

It does not happen when changing level while in-game using the IDCLEV cheat.


I'm attaching:
- the map I'm using to test this
- console output when warping (with the game crashing)
- console output when warping, but using also the "-nomonsters" parameter (this does not trigger the crash)
- console output when changing level with IDCLEV (this also does not trigger the crash)

[ShowRoom2.zip](https://github.com/MrAlaux/Nugget-Doom/files/9843867/ShowRoom2.zip)
[nugget-doom-warp.log](https://github.com/MrAlaux/Nugget-Doom/files/9843909/nugget-doom-warp.log)
[nugget-doom-warp-nomonsters.log](https://github.com/MrAlaux/Nugget-Doom/files/9843910/nugget-doom-warp-nomonsters.log)
[nugget-doom-idclev.log](https://github.com/MrAlaux/Nugget-Doom/files/9843892/nugget-doom-idclev.log)

**Comment by MrAlaux** [comment]
> Hi, I'm facing a crash on startup when the lock-on feature is enabled.
The error message is "I_SignalHandler: Exit on Floating-point error (Signal 8)"

Thanks for the report. 24e58f53863a7d94bf3532fec447b23f202e8b33 seems to fix it.

**Comment by ghost** [comment]
> Still awaiting for feedback on the allegedly-faulty vertical lock-on.
> 
> In the meanwhile, I've done something regarding horizontal autoaim: [307edb4](https://github.com/MrAlaux/Nugget-Doom/commit/307edb4bd1c40f1fdc0435ba536393d02f288981). It's probably not what you expected, but we can try it.

Sorry, i was busy in the last few days, sadly i can't test it because the latest master now fails to launch.
![image](https://user-images.githubusercontent.com/68514898/197394581-0105f1fc-5676-4d29-9641-4fd5332c4f0d.png)
I will open an issue about that and come back to this after that gets resolved

**Comment by ghost** [comment]
Alright, i found what causes the lock on crosshair to break.
The error is provoked by having the resolution set to the (default) low res mode.

https://imgur.com/FE2WwY3.png being above the enemy on low res mode
https://imgur.com/h0zM3dl.png being above the enemy on high res mode
https://imgur.com/i4EHtmq.png being below the enemy on low res mode
https://imgur.com/z3vtLkv.png being below the enemy on high res mode

it might be a bit hard to see from this distance (this is kind of why the crosshair is so useful on low res making this bug ruin the corsshairs whole point) but the crosshair is waaaay off

**Comment by ghost** [comment]
also the crosshair just mindlessly locks onto the center of the enemy, while in crispy it aims to the parts of the enemy that's actually visible if the enemy's body is obscured in any way, matching what the autoaim does

nugget:
![Screenshot_20221024_224835](https://user-images.githubusercontent.com/68514898/197627360-dc6f95ed-ff10-4f67-959a-4353ca53d4ae.png)
crispy:
![Screenshot_20221024_225025](https://user-images.githubusercontent.com/68514898/197627405-d9cabcd7-adff-4937-af9b-95d4131b545b.png)
zoomed in crispy screenshot:
![image](https://user-images.githubusercontent.com/68514898/197627548-b73baa24-6d7b-438d-adb1-e80a0a2971f5.png)

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/68514898/197627703-06facf74-bfff-4bdf-9d0d-26a403827e22.png)
a different angle (so the enemy's head is visible)

**Comment by MrAlaux** [comment]
I did eventually find out that the crosshair had issues in lowres, and I'm pretty sure that ef32013eb05e3de795826f7395fcf794c48aa5b4 fixed it. Said commit was pushed before the one that causes crashes in your system, so you should be able to test it.

I'm also aware that the lock-on draws the crosshair in the middle point of the target's bounding box, but I didn't mind it and therefore don't have a solution yet.

**Comment by MrAlaux** [comment]
I think I'll keep this as-is for now:

Regarding the projected crosshair, implementing it is not worth it for me, considering the necessary effort and the as-of-now singular request.

Regarding the target lock-on, its current behavior - at least in terms of locking onto a potentially obstructed portion of the target - appears identical to that of DSDA-Doom, so I'll take it as good enough.
