### ISSUE TITLE
[bug report] Using MDK in any way crashes the game

### ISSUE THREAD

**Issue by ghost** [MrAlaux/Nugget-Doom#16]
The crash message I get:
![image](https://user-images.githubusercontent.com/68514898/194784002-1311b82b-c2b1-448d-b2ac-fe4949654c3c.png)

**Comment by MrAlaux** [comment]
Are you able to trigger the crash consistently? That is, does MDK *always* trigger the crash?

**Comment by ghost** [comment]
yesterday's builds crashed the game every time, today i compiled the game again from the latest source and now it no longer crashes the game

**Comment by MrAlaux** [comment]
Odd, it shouldn't have been fixed...
