### ISSUE TITLE
[silly feature request] Ability to remove the face background for the status bar when using the crispy hud

### ISSUE THREAD

**Issue by ghost** [MrAlaux/Nugget-Doom#18]
![image](https://user-images.githubusercontent.com/68514898/194784303-ff1005a4-defb-47ed-9889-45195c1d28e2.png)
It sounds silly, might end up being hard to see and would just add yet  more hud option into the bunch but it sounds but it has a slim chance of looking kind of good

**Comment by MrAlaux** [comment]
Do you mean the face background?

**Comment by ghost** [comment]
yes, apparently i forgot to mention the core part of my request...

**Comment by MrAlaux** [comment]
Since you're not the first to ask for changes in the HUD, I decided to finally implement a customizable HUD: check out the `nughud` branch. There's a text file explaining how the implementation works.

It should also help with #13.

**Comment by MrAlaux** [comment]
Well, 3077925735d483c0eeb79ff4632268ace1e4bcc0 has been merged into the master. It should let you customize the Crispy HUD as you wish.

**Comment by liPillON** [comment]
hey thank you for this feature!
would you consider adding support for loading graphic patches as well?
this way one could add, let's say, STIMA0 alongside the health counter and BON2C0 alongside the armor counter

I'm a fan of the fullscreen hud for International Doom, so replicate it in woof/nugget would be fantastic

**Comment by MrAlaux** [comment]
I like the idea, I'll see what I can do.

**Comment by MrAlaux** [comment]
>would you consider adding support for loading graphic patches as well?

@liPillON it's done: 385d77a8e43cca8ef34b4a290bf656301d43da89. Remember, there's a guide on the `docs` folder explaining how it works.

**Comment by liPillON** [comment]
Sweet! 
I've been able to replicate how the InternationalDoom hud works

 
[nughud-interdoom.zip](https://github.com/MrAlaux/Nugget-Doom/files/9846104/nughud-interdoom.zip)


![nughud-interdoom](https://user-images.githubusercontent.com/48625273/197383819-80d6f167-0e00-46bd-a44b-add2122d4e45.png)

![nughud-interdoom-wide](https://user-images.githubusercontent.com/48625273/197383821-cd375ae9-2b15-4a2d-959c-0761042900e4.png)

**Comment by MrAlaux** [comment]
Glad to see it working. Mind if I were to use these screenshots as a preview for the Nugget HUD when announcing the next release?

**Comment by liPillON** [comment]
sure, go ahead!
