### ISSUE TITLE
[feature request] Ability to reverse the order of messages showing up when "multi line messages" are neabled well as turning off past messages showing up

### ISSUE THREAD

**Issue by ghost** [MrAlaux/Nugget-Doom#20]
![image](https://user-images.githubusercontent.com/68514898/194950675-952d18f0-ab07-42b9-9a00-d1cef8427eb4.png)
I would like to have past actions fade out and not show up after a certain amount of time and the ability to have the bottom message show the latest action and the top one showing the oldest

**Comment by MrAlaux** [comment]
Got one part done, turns out the scroll direction could be toggled before but the feature was removed: dc4ed3b628384200800a054757fc7ced08d0f999
