### ISSUE TITLE
[feature request] PSXDoom style screen melting (loading screen) from "International Doom"

### ISSUE THREAD

**Issue by ghost** [MrAlaux/Nugget-Doom#22]
![image](https://user-images.githubusercontent.com/68514898/194929622-67d125bf-3ccb-4a17-86e9-69a642cf597a.png)

**Comment by MrAlaux** [comment]
For the time being, I'd like to avoid having to add new graphics to the executable. Since that's a requirement for this feature, it won't be worked upon for now.

**Comment by ghost** [comment]
Fair enough, I will bring these kind of features up when the time comes for that.
