### ISSUE TITLE
UMAPINFO episodes do not show

### ISSUE THREAD

**Issue by Xeebleton** [MrAlaux/Nugget-Doom#27]
in the latest release, episodes set by UMAPINFO do not display (tested with Eviternity and Valiant)

**Comment by MrAlaux** [comment]
Can you verify if the same issue is present in the latest release and latest master of Woof? As far as I'm concerned, this should work exactly how it does in Woof.

**Comment by Xeebleton** [comment]
just tested it, I can confirm that they do not appear in woof either

**Comment by MrAlaux** [comment]
If that's true for the latest master of Woof, then you should open an issue there.

**Comment by ghost** [comment]
Can confirm that UMAPINFO episodes don't show up on any source port other then cheesey doom
