### ISSUE TITLE
[feature request] per-IWAD save sets

### ISSUE THREAD

**Issue by Xeebleton** [MrAlaux/Nugget-Doom#29]
I would like each IWAD to have their own set of saves, like in ports such as GZDoom, instead of the port only having one universal save set.

**Comment by MrAlaux** [comment]
[Something similar](https://github.com/fabiangreffrath/woof/issues/793)  is being discussed for Woof.

**Comment by MrAlaux** [comment]
Should be fixed by b22a56e.
