### ISSUE TITLE
Linux build failure (quick_exit) 

### ISSUE THREAD

**Issue by atsb** [MrAlaux/Nugget-Doom#3]
You are using 'quick_exit' which on Linux is declared in the stdlib:
```
/usr/include/stdlib.h:628:13: note: previous declaration of ‘quick_exit’ with type ‘void(int)’
  628 | extern void quick_exit (int __status) __THROW __attribute__ ((__noreturn__));
```

I have done a build that renamed it to 'doom_quick_exit' however since it is your source port, I'll leave you to give it a name that fits your vision better.  But whatever it is, it cannot be quick_exit :)

**Comment by MrAlaux** [comment]
Thanks for the notice!
