### ISSUE TITLE
[Feature Request] Alternative secret message sounds

### ISSUE THREAD

**Issue by TheDwellerInDarkness** [MrAlaux/Nugget-Doom#30]
While I like the option to display the secret message notification, the default sound isn't exactly the one I like. So, I'd like to suggest the ability to choose alternative sounds for it, ones that could likely be picked out by the developers and/or community. The one I'd suggest is the GZDoom sound for secrets, or one similar to it. 

Alternatively, if someone were able to make wads with alternatives to the default one, I think it would be acceptable for me. I'd do it myself if I knew and understood how to, but I don't. 

Thank you for any answers or help with this request, though

**Comment by MrAlaux** [comment]
I assume you're unaware of this: a few source ports, such as Crispy, Woof, and of course Nugget, look for a `DSSECRET` sound lump to play when a secret is revealed. If said lump can't be found, they default to `DSITMBK`. Providing a `DSSECRET` lump is done by loading a WAD that contains one (it must be in Doom Sound format, of course). [**This thing**](https://www.doomworld.com/forum/topic/126167-my-take-on-the-sprite-fixing-project-new-offsets-and-more-rev-2-released/?tab=comments#comment-2450703) I made happens to provide GZDoom's secret revealed SFX.

**Comment by TheDwellerInDarkness** [comment]
> I assume you're unaware of this: a few source ports, such as Crispy, Woof, and of course Nugget, look for a `DSSECRET` sound lump to play when a secret is revealed. If said lump can't be found, they default to `DSITMBK`. Providing a `DSSECRET` lump is done by loading a WAD that contains one (it must be in Doom Sound format, of course). [**This thing**](https://www.doomworld.com/forum/topic/126167-my-take-on-the-sprite-fixing-project-new-offsets-and-more-rev-2-released/?tab=comments#comment-2450703) I made happens to provide GZDoom's secret revealed SFX.

Do I just need to load that WAD file and it'll work, or extract the SFX from it in some form?

**Comment by MrAlaux** [comment]
> Do I just need to load that WAD file and it'll work, or extract the SFX from it in some form?

Loading that WAD as is should get it working. Of course, that means loading everything else in the WAD, which you might not want, in which case you can open my WAD, extract the `DSSECRET` lump and place it all by itself in a new, empty WAD. Said new WAD doesn't necessarily have to be empty, but unless you're planning to provide other things, it'll most likely have no other contents. I believe you're using a custom NUGHUD, so you could put the sound in that WAD to keep matters simpler.

**Comment by TheDwellerInDarkness** [comment]
> > Do I just need to load that WAD file and it'll work, or extract the SFX from it in some form?
> 
> Loading that WAD as is should get it working. Of course, that means loading everything else in the WAD, which you might not want, in which case you can open my WAD, extract the `DSSECRET` lump and place it all by itself in a new, empty WAD. Said new WAD doesn't necessarily have to be empty, but unless you're planning to provide other things, it'll most likely have no other contents. I believe you're using a custom NUGHUD, so you could put the sound in that WAD to keep matters simpler.

What tools would I need to extract the lump and add it to NUGHUD?

**Comment by MrAlaux** [comment]
> What tools would I need to extract the lump and add it to NUGHUD?

We Doom modders usually use [**SLADE**](https://slade.mancubus.net/index.php?page=downloads).

**Comment by TheDwellerInDarkness** [comment]
I've got SLADE open, what do I do now?

**Comment by MrAlaux** [comment]
Open up both the NUGHUD WAD and my Sprite Fix... thing WAD. Look for the `DSSECRET` lump (item) in the lump list of the Sprite Fix WAD and copy it, then paste it in the NUGHUD WAD's lump list and save it. I believe you can find the "Open" button by yourself.

**Comment by TheDwellerInDarkness** [comment]
I figured it out and tested it out with all the NUGHUD variants, so here's a ZIP with the ones I changed in case anyone else wants that specific DSSECRET sound along with the HUDs.

[NUGHUDGZDSSECRET.zip](https://github.com/MrAlaux/Nugget-Doom/files/9985647/NUGHUDGZDSSECRET.zip)

**Comment by MrAlaux** [comment]
Well done!

And with that, is the issue (well, feature request) fixed?

**Comment by TheDwellerInDarkness** [comment]
> Well done!
> 
> And with that, is the issue (well, feature request) fixed?

Pretty much, but is it possible to drop the NUGHUDs or the DSSECRET wad file I made into the autoload folder and have it work that way? I use DoomLauncher, but I'm interested in having those be loaded without it

**Comment by MrAlaux** [comment]
Heh, I do that myself, works perfectly for me. You may want to drop them in the `doom-all` autoload folder; not sure if that one autoloads WADs for every IWAD or for both Doom IWADs (that is, Doom 1/Ultimate Doom and Doom 2), but regardless, you shouldn't have any issues.

Here's a tip: sometimes you can test things yourself and see if they work. Don't get me wrong, I'm not bothered at all, but I'm pretty sure you'll get answers much quicker like that.
