### ISSUE TITLE
nughud regression 

### ISSUE THREAD

**Issue by liPillON** [MrAlaux/Nugget-Doom#31]
I wanted to try the new "Automap Dark Overlay" feature and downloaded [this](https://github.com/MrAlaux/Nugget-Doom/actions/runs/3466094980) autobuild.

I've noticed that at screensize=13 and with hud_displayed set to either 1 or 0, patches added using the nughud lump are always drawn (other nughud elements such as ammo/armor counters are not).

These screenshots show what's happening at various screensize/hudactive/automap settings:

size12
![size12](https://user-images.githubusercontent.com/48625273/201866176-58ec0a78-0f72-4496-a9f1-eb23bc2a74f9.png)

size13-hudOFF
![size13-hudOFF](https://user-images.githubusercontent.com/48625273/201866182-be1beb80-d18b-49b8-8c45-b731a30329f6.png)

size13-hudON
![size13-hudON](https://user-images.githubusercontent.com/48625273/201866184-149897e3-bcff-494b-a071-822d97736a00.png)

size13-hudON-mapON-overlayOFF
![size13-hudON-mapON-overlayDARK](https://user-images.githubusercontent.com/48625273/201866186-496e1734-6038-4e02-bbb5-bd25218d1e5f.png)

size13-hudON-mapON-overlayDARK
![size13-hudON-mapON-overlayOFF](https://user-images.githubusercontent.com/48625273/201866190-8eb46649-483e-45e9-9729-caae829b97f5.png)

size13-hudON-mapON-overlayON
![size13-hudON-mapON-overlayON](https://user-images.githubusercontent.com/48625273/201866192-62489bb3-acf2-423f-8c89-0ab299781aff.png)

**Comment by MrAlaux** [comment]
Thanks for the report! Should be fixed by 7d01e5970d6ce43b3de774eab3be16497714e9e4.
