### ISSUE TITLE
issue with "Weapon Bobbing Percentage"

### ISSUE THREAD

**Issue by liPillON** [MrAlaux/Nugget-Doom#35]
Hi! I wanted to try out this new feature and downloaded the latest autobuild.
I changed it to "0" and this lead to something funny, in conjunction with the [Minicharge pwad](https://www.doomworld.com/forum/topic/109195-minicharge-mbf-resourcemod-v13-new-bfg-sprites-52520/) by Tango.
Basically the sprite of the weapon keep raising indifinetely instead of stopping in the usual position at the bottom of the screen.

This happens regardless of screensize, view bobbing or any other settings (tested it with a .cfg generated from scratch).
It goes away when setting "Weapon Bobbing Percentage" to any value greater than "0".

I'm using complevel 11, as the pwad requires it.

Thank you in advance for taking a look at this!

**Comment by MrAlaux** [comment]
Oh my god!

**Comment by liPillON** [comment]
actually, this happens also in [this](https://github.com/MrAlaux/Nugget-Doom/actions/runs/3881094676) autobuild so it must be something unrelated to the weapon/view bobbing decoupling
setting "options>setup>weapons>cosmetic>bobbing percentage" to "0" lead to this "bug"

I see that you already committed a fix :)

**Comment by MrAlaux** [comment]
> I see that you already committed a fix :)

Indeed, it works fine for me, but I'd be glad if you could try it yourself just in case.

**Comment by liPillON** [comment]
Just tested it, everything looks fine!

**Comment by MrAlaux** [comment]
Alrighty, thanks!

God, seeing that was shocking...
