### ISSUE TITLE
[Request] Quad-Resolution support from Inter-Doom

### ISSUE THREAD

**Issue by MrAlaux** [MrAlaux/Nugget-Doom#37]
As requested in the [Doomworld thread](https://www.doomworld.com/forum/post/2597204).

See:

https://github.com/JNechaevsky/inter-doom/commit/97a4ce00b708f331f6dd807827513984fbc119f8
https://github.com/JNechaevsky/inter-doom/commit/3c4c3dc515c6afedba59c10a91ba99a6c627c77b
https://github.com/JNechaevsky/inter-doom/commit/6b445ffda8a04897484374300e3974be14239ed9

**Comment by JNechaevsky** [comment]
Colleagues, just for the history -- the way it was done in Inter-Doom is an overkill, nothing more than pure mess of `quadres` shifting on top of outdated video code. In actual Crispy Doom code it's just a question of four (!!!) lines of code: `MAXWIDTH/HEIGHT` macroses should be shifted left by one, as well as status bar background buffer. Also, `hires` value should accept `2` in Crispness menu. And that's it, nothing more needed.

Let's just hope that everyone who will use it, will understand that it's not slow, it's _expensive_ for single-thread render. 
But damn, it's awesome! And if user's PC can handle it, why not?

**Comment by liPillON** [comment]
dropping this here, as well as at doomworld's forums:

> I've noticed that the "renderer resolution" setting does not seem to be initialized at program startup: i've set it to "2" in all my cfg files but when I launch the game, the actual resolution is still 400p
> The settings menu report it as 800p, but I need to change it to any value and then set it back to 800p to actually get the desired resolution

**Comment by ceski-1** [comment]
@liPillON What's the command line you use to launch the game? And can you share your config?

**Comment by liPillON** [comment]
oh right, the command line... I've spent half an hour trying various changes to my cfgs and never bothered to check the command line...

I had my launcher set up to always append the "-hires" parameter, removing it fixed my issue

sorry guys

**Comment by ceski-1** [comment]
@MrAlaux I would suggest changing [this line](https://github.com/MrAlaux/Nugget-Doom/blob/460607f46976cbb7dd9dcc6ebae182baacdc28e4/src/i_video.c#L1212) to preserve the user's setting:
```diff
-if (M_CheckParm("-hires"))
+if (M_CheckParm("-hires") && !hires)
```

**Comment by MrAlaux** [comment]
Hm, it's a bit of a double-edged sword; users may rely on it to set 2X specifically. We _could_ add new parameters (e.g. `-4x`, `-hiresmax`), but I don't think the existing `-nohires` and `-hires` are widely used to begin with.

**Comment by ceski-1** [comment]
@MrAlaux I saw that line when working on the PR, went through the same thought process, and opted to keep the existing behavior. Ultimately, the `-hires` parameter no longer matches the `hires` config key behavior so either live with that (and the bug reports that follow) or make them match. Other ideas: `-hires <0-3>` or remove `-hires` completely. I'll leave it to you.
