### ISSUE TITLE
Wall/sprite lighting isn't adjusted to FOV

### ISSUE THREAD

**Issue by MrAlaux** [MrAlaux/Nugget-Doom#40]
Unlike with flats, lighting of walls and sprites changes based on FOV as if the player were physically getting closer or further away from them.

Doom Retro doesn't have this issue; what does it do differently?

**Comment by MrAlaux** [comment]
Hey @bradharding, now that you're around: any ideas on why this could be? Perhaps you had already encountered this issue while implementing FOV into DR and could give a tip, I'm not expecting you to go through Nugget's source code trying to track it down.

**Comment by bradharding** [comment]
After a very quick look, maybe the following would help? https://github.com/bradharding/doomretro/commit/84ef30f32f5d8d83bbd5f7d6518c683afbd72bfa

**Comment by MrAlaux** [comment]
Perhaps I missed something, but I tried with that and not only did it not fix the issue, it actually reverted the diminishing light effect:
![imagen](https://github.com/MrAlaux/Nugget-Doom/assets/73968015/a1cc6d19-c508-47fa-ae60-c792668fbf89)

That's what usually happens every time I try to fix this issue.

**Comment by bradharding** [comment]
Ah, sorry, didn't see this 'til now. Not sure what's happening. I'll find some time to compare my code and yours. (Congrats on the release BTW!)

**Comment by MrAlaux** [comment]
> I'll find some time to compare my code and yours.

Well, if you'd like to. Again, you don't _have_ to do it.

> Congrats on the release BTW!

Thanks!

**Comment by MrAlaux** [comment]
I just found out that, allegedly, wall/sprite lighting is calculated based on the scale of the texture. That's most likely what's going on here.
