### ISSUE TITLE
[request] font override in NUGHUD

### ISSUE THREAD

**Issue by liPillON** [MrAlaux/Nugget-Doom#41]
Hi!
I know you're busy merging latest woof release into nugget for now, buut..
Would you consider adding to NUGHUD one or more settings that would let modders customize the font used?
eg: a string representing a new prefix to use instead of "STTNUM" 
Currently modders must replace the stock lumps with their own, ending up overriding them in standard stbar mode too

I see two scenarios where this would be helpful
a) being able to preserve the stbar as intended by the mappers
b) being able to autoload the nughud wad without having the wad loaded using "-file" override the hud lumps

What do you think?

**Comment by MrAlaux** [comment]
I'm actually done merging Woof 11.0.0's changes already, don't worry about it. On that note, I'm actually considering a release in a few days.

There are three number fonts used for the Status Bar: `STTNUM`, `STGNUM` and `STYSNUM`, which in vanilla Doom correspond to big red numbers, small grey numbers and small yellow numbers respectively. Which of these exactly are you suggesting alternatives to?

Regardless, I do like the idea and it sounds doable, although I might just stick to hardcoded names like `NHTNUM`, `NHGNUM` and `NHYNUM`. Not as flexible as what your suggestion implies, but for that matter, NUGHUD isn't _that_ flexible either.

**Comment by liPillON** [comment]
Being able to replace any of the 3 fonts would be ideal.
Let's not forget also STTMINUS and STTPRCNT

I would not mind using hardcoded names, if this will let you keep the implementation of the feature simple.
What if no lumps are provided, though? I guess the engine will fall back to the stock ones, right? 

Keep up the good work!

**Comment by MrAlaux** [comment]
> What if no lumps are provided, though? I guess the engine will fall back to the stock ones, right?

I'd try to make it so that the NUGHUD fonts are only used if all characters of a given set are provided. For example, the `NHY` set would only be used if `NHYNUM0` through `NHYNUM9` are provided. It should be possible to make it work without all custom characters by using standard font characters in place of missing custom characters, but that would probably be a considerable amount of effort for something that would ultimately look off.

**Comment by MrAlaux** [comment]
So, 7af75fb:
![imagen](https://user-images.githubusercontent.com/73968015/237049834-ea75b27d-8c42-44d4-ade0-400f2ce0e790.png)

Those weapon graphics are actually the Arms numbers, replaced with a custom font. Turns out the code was somewhat prepared to have unique weapon available/unavailable numbers but they ended up reusing the yellow Ammo numbers for the former.

Anyways, this is just a preview of what can be done, as you can also provide alternatives for `STTNUM` and `STYSNUM`. Get a build of the latest master, check out the updated NUGHUD guide for reference and try it yourself!

**Comment by liPillON** [comment]
Sweet!
I'll toy around with this for a while..

**Comment by liPillON** [comment]
hmm it just occured to me that this could be extended to override "STKEYS" lumps also ;)

**Comment by MrAlaux** [comment]
For that matter, I could also add support for alternative Face graphics.

**Comment by MrAlaux** [comment]
Alright, alternative Keys graphics implemented in 0c63826. Mind testing it a bit?

Implementing alternative Face graphics is a little bit trickier, though, and a bit overkill in my opinion, so I might just omit that for now.

**Comment by liPillON** [comment]
hey I finally had some time to experiment with the latest changes
I created a "minimal" hud which tries something fancy with the weapon slots

Screenshots:
[starting equipmet](https://github.com/MrAlaux/Nugget-Doom/assets/48625273/190359aa-4912-4e13-aac0-00668d4cf2b2)
[picked up armor, chainsaw, shotgun, rocketlauncher, plasmarifle](https://github.com/MrAlaux/Nugget-Doom/assets/48625273/17f7edc1-be79-4ca9-a611-0a3a2c725531)
[picked up also chaingun, supershotgun, bfg and a few keys](https://github.com/MrAlaux/Nugget-Doom/assets/48625273/af4c48aa-9544-4667-b871-e8c4f0e72af6)

Notice how icons for ammo change to reflect the "level" of the available weapon.

Here it is, any feedback is appreciated!
[NUGHUD_Minimal.zip](https://github.com/MrAlaux/Nugget-Doom/files/11489716/NUGHUD_Minimal.zip)

**Comment by MrAlaux** [comment]
Judging from the screenshots, it looks pretty damn clever. I'll check it out myself when I can.

Anyways, any issues or more suggestions? Otherwise, I think we're done here.

**Comment by liPillON** [comment]
nah, working on this I did not feel like I was missing anything.. it all looks good for primetime

obviously the current implementation of this custom hud is tied to the stock Doom iconography for keys and ammunition, so it will clash with any pwad that replaces those sprites.. but this can not be managed by the port and so it's on me to figure this out, if/when people will complain abour it

**Comment by MrAlaux** [comment]
Alright then, I'm closing this issue. Thanks for the idea and for testing it!

**Comment by MrAlaux** [comment]
Hey @liPillON, do you mind if I use one of these screenshots...

> Screenshots:
> [starting equipmet](https://github.com/MrAlaux/Nugget-Doom/assets/48625273/190359aa-4912-4e13-aac0-00668d4cf2b2)
> [picked up armor, chainsaw, shotgun, rocketlauncher, plasmarifle](https://github.com/MrAlaux/Nugget-Doom/assets/48625273/17f7edc1-be79-4ca9-a611-0a3a2c725531)
> [picked up also chaingun, supershotgun, bfg and a few keys](https://github.com/MrAlaux/Nugget-Doom/assets/48625273/af4c48aa-9544-4667-b871-e8c4f0e72af6)

... for the 1.14 release post on Doomworld?

**Comment by liPillON** [comment]
sure, no problem!
