### ISSUE TITLE
400p performance regression?

### ISSUE THREAD

**Issue by liPillON** [MrAlaux/Nugget-Doom#44]
Hi! 
Woof made some optimizations recently, see here:
https://www.doomworld.com/forum/post/2660078

Out of curiosity, I've performed the same tests in Nugget - mainly to check out how the 800p resolution would impact performance in such a case (it's my understanding that Woof's recent optimizations have not been merged in nugget yet, so I was expecting to get framerates comparable only to Woof's 11.2 release build).

I discovered that up until [run #46](https://github.com/MrAlaux/Nugget-Doom/actions/runs/5127933804) performance at 400p rendering resolution was the same in both ports.
Since [run #54](https://github.com/MrAlaux/Nugget-Doom/actions/runs/5229458736) there has been a sensible drop in max fps (from 63 to 33).

@MrAlaux @ceski-1 what are your thoughts on this?

**Comment by MrAlaux** [comment]
All I can say for now is that, while working on the higher-resolution modes, @ceski-1 and I ran benchmarks on a total of 3 computers, and there seemed to be hardly any impact in performance.

Just in case, could you benchmark the latest run as of now, and compare it to Woof 11.2.0?

**Comment by liPillON** [comment]
using PLN.WAD, which stresses the engine with over 7K visplanes:
- woof [11.2](https://github.com/fabiangreffrath/woof/releases/tag/woof_11.2.0) x64 => [63 fps](https://github.com/MrAlaux/Nugget-Doom/assets/48625273/e677fa6a-b00a-4cdd-9d86-ce0d3a238a3f)
- nugget [automated build #62](https://github.com/MrAlaux/Nugget-Doom/actions/runs/5287144086) x64 => [33 fps](https://github.com/MrAlaux/Nugget-Doom/assets/48625273/25270934-b19f-41e8-9637-5f670598c4af)


using EVITERNITY.WAD MAP26, a more realistic (and still quite taxing) end-user scenario
- woof [11.2](https://github.com/fabiangreffrath/woof/releases/tag/woof_11.2.0) x64 => [134 fps](https://github.com/MrAlaux/Nugget-Doom/assets/48625273/2fb16a4e-8cbd-42ef-846b-c9c5c32ed929)
- nugget [automated build #62](https://github.com/MrAlaux/Nugget-Doom/actions/runs/5287144086) x64 => [115 fps](https://github.com/MrAlaux/Nugget-Doom/assets/48625273/728d3c7e-2e48-4853-a220-ed6f586b4dc4)


Keep in mind that in Eviternity both the framerate and the visplane count fluctuate quite a bit, so I waited to capture the absolute maximum framerate for each port.


I'm using a win11-based, i7-1260p-powered laptop.

**Comment by liPillON** [comment]
OK I ended up running some timedemos and gathered the resulting average framerates...
I guess one could say that the difference is there, but at such framerates is probably negligible.

<table>
<tr>
 <th>pwad             <th>nugg 1.14 <th>woof 11.2 <th>nugg git <th>woof git
<tr>
 <td>eviternity       <td>318       <td>315       <td>290      <td>325
<tr>
 <td>alien vendetta   <td>587       <td>575       <td>550      <td>591
<tr>
 <td>saturnine chapel <td>262       <td>260       <td>245      <td>265
<tr>
 <td>grove            <td>249       <td>249       <td>238      <td>254
</table>



PS: between each run I let the laptop cool down a bit, so the results should not have been affected by any thermal throttling



demos used:
- EVITERNITY.WAD, CL11, MAP26, UV MAX [demo](https://dsdarchive.com/files/demos/eviternity/44536/evit26-658.zip)
- AV.WAD, CL2, MAP20, UV MAX [demo](https://dsdarchive.com/files/demos/av/28588/av20-1357.zip)
- SATCHAP.WAD, CL9, MAP01, UV MAX [demo](https://dsdarchive.com/files/demos/satchap/20510/satchap-706.zip)
- GROVE.WAD, CL9, MAP01, UV MAX [demo](https://dsdarchive.com/files/demos/grove/12807/grov-724.zip)


builds used:
- nugg 1.14: [official release](https://github.com/MrAlaux/Nugget-Doom/releases/tag/nugget-doom-1.14.0) 
- woof 11.2: [official release](https://github.com/fabiangreffrath/woof/releases/tag/woof_11.2.0) 
- nugget git: [automated build #62](https://github.com/MrAlaux/Nugget-Doom/actions/runs/5287144086) 
- woof git: [automated build #785](https://github.com/fabiangreffrath/woof/actions/runs/5287929619)

**Comment by ceski-1** [comment]
@liPillON Thanks for the details, I was able to confirm your findings.

@MrAlaux This is due to various arrays being dependent on the large `MAX_SCREENWIDTH` and `MAX_SCREENHEIGHT` values. A long term solution is to eliminate the use of those macros and allocate every array that depends on those values at runtime using the correct `hires` value rather than `MAX_HIRES`. For reference, see Eternity Engine's commits [here](https://github.com/team-eternity/eternity/commit/6ac31a983540f0c1e2506e8630c9c78e40367d5e) and [here](https://github.com/team-eternity/eternity/commit/566124694e4b1b1ac95d2263780a451ea23fb082). Those aren't trivial changes and I don't have enough experience to execute it properly, so I don't plan on fixing this. This is an experimental feature and there are issues, as expected. For now, I recommend setting `MAX_HIRES` to 1 until this feature is more mature. That eliminates the performance regression.

**Comment by liPillON** [comment]
IIUIC the size of these arrays is determined at compile time and this requires their upper bounds to be set accordingly to the maximum user-selectable resolution.

So, even if I were to launch the game with the -nohires parameter, forcing 200p rendering, the arrays' sizes would be those required by 1600p rendering.

This has an impact on all routines/iterators that read and/or write data to these arrays.

Correct?



What if the maximum available resolution would be 800p? There should be a 50% reduction in size for those arrays and maybe a bit of performance would be gained back?

**Comment by ceski-1** [comment]
> Correct?

Yes.

> What if the maximum available resolution would be 800p?

That's already been tested. If Nugget is compiled with `MAX_HIRES` of 2 (forcing the upper limit to 4x, aka 800p), some performance returns but there's still a drop in the stress test wads. In "normal" wads the difference is negligible.

**Comment by MrAlaux** [comment]
> For now, I recommend setting `MAX_HIRES` to 1 until this feature is more mature. That eliminates the performance regression.

Well, I wouldn't like to give up 4X support at this point.

What if we had dedicated arrays for each resolution? Very primitive, yes, but could it work? Although, implementing that might be a similar effort to having dynamic allocation (what Eternity does), at which point I could try to do that.

On another note, how come we didn't encounter these regressions at first?

**Comment by ceski-1** [comment]
I think the effort to implement the changes is the same either way but dynamic allocation is better in the long run. Please give it a shot.

> On another note, how come we didn't encounter these regressions at first?

All the benchmarking we did was with the 4x branch and on maps far less demanding than the above visplane wad ([pln.wad)](https://github.com/fabiangreffrath/woof/issues/1107#issuecomment-1591028958). 8x was only added after merging the 4x branch. The workload increases by 1, 4, 16, 64 times for hires 0, 1, 2, 3, respectively: `pow(2, hires) * pow(2, hires)`.

**Comment by liPillON** [comment]
What about reverting to `MAX_HIRES 2` in the meantime, as a stopgap solution?

I would then perform the same benchmarks again.

**Comment by MrAlaux** [comment]
> What about reverting to `MAX_HIRES 2` in the meantime, as a stopgap solution?

We could do that for the time being, although I've been thinking about the dynamic allocation approach and gained quite an interest in it since it *might* end up making Nugget perform better than Woof, since the latter is always working with arrays sized for 21:9 400p.

**Comment by liPillON** [comment]
Since a couple more optimizations have landed in woof, I thought updating the performance comparison would have been interesting. I added the last column, which refers to woof's [automated build #798](https://github.com/fabiangreffrath/woof/actions/runs/5311998658)

<table>
<tr>
 <th>pwad             <th>nugg 1.14 <th>woof 11.2 <th>nugg artifacts 62<th>woof artifacts 785 <th>woof artifacts 798
<tr>
 <td>eviternity       <td>318       <td>315       <td>290      <td>325      <td>338
<tr>
 <td>alien vendetta   <td>587       <td>575       <td>550      <td>591      <td>609
<tr>
 <td>saturnine chapel <td>262       <td>260       <td>245      <td>265      <td>268
<tr>
 <td>grove            <td>249       <td>249       <td>238      <td>254      <td>258
<tr>
 <td>demonastery      <td>          <td>471       <td>         <td>         <td>479
</table>

**Comment by MrAlaux** [comment]
Hey @liPillON, could you try [run #67](https://github.com/MrAlaux/Nugget-Doom/actions/runs/5318294534)? From what little testing I did, performance is the same in most cases, _except_ in timedemos where it was considerably worse. Perhaps you'll get different results, but I'm not getting my hopes up.

**Comment by liPillON** [comment]
I'll post the results in #45

**Comment by liPillON** [comment]
I'm currently testing run74 generated from #47 (max_hires 3, static arrays, woof optimizations)
But I'm going to also test the latest changes in #45 using run76 (max_hires 3, dynamic arrays, no optimizations) 

I'll post the results here, to avoid fragmenting the discussion over several pr threads.

**Comment by liPillON** [comment]
Phew, all done...
Results displayed in the following table, comparing them with tests on previous builds.

PR 45 (dynamic arrays allocation) has basically the same performance as the current master.
PR 46 (1600p support removed) has no clear benefits over the current master.
PR 47 (woof optimizations) brought improvements across the board: still not back at nugget 1.14 performance level, but results are better than woof 11.2 (which lacks 800p/1600p support).


|VISPLANE TEST MAP    |woof 11.2 |woof git |nugg 1.14 |nugg git |nugg pr46 |nugg pr45 |nugg pr47 |
|---------------------|----------|---------|----------|---------|----------|----------|----------|
|PLN.WAD              |60        |100      |59        |35       |45        |33        |93        |

|TIMEDEMOS            |woof 11.2 |woof git |nugg 1.14 |nugg git |nugg pr46 |nugg pr45 |nugg pr47 |
|---------------------|----------|---------|----------|---------|----------|----------|----------|
|alien vendetta MAP20 |605       |643      |637       |612      |601       |607       |611       |
|demonastery          |458       |508      |498       |460      |457       |438       |479       |
|eviternity MAP26     |337       |358      |347       |324      |328       |315       |344       |
|grove                |256       |266      |264       |253      |258       |248       |267       |
|planisfere 2         |363       |379      |370       |343      |353       |337       |365       |
|saturnine chapel     |272       |279      |275       |263      |271       |260       |270       |
|sunlust MAP30        |275       |285      |278       |258      |269       |259       |281       |


BUILDS:
- woof 11.2: current official release
- woof git: master branch (visplane optimizations) artifacts run 798
- nugget 1.14: current official release
- nugget git: master branch (MAX_HIRES 3), artifacts run 69
- nugget pr46: master branch (MAX_HIRES 2), artifacts run 71
- nugget pr45: master branch (MAX_HIRES 3 + dynamic array allococation), run 76
- nugget pr47: master branch (MAX_HIRES 3 + visplane optimizations), run 74

DEMOS:
- https://dsdarchive.com/files/demos/av/28588/av20-1357.zip
- https://dsdarchive.com/files/demos/demonastery/48438/demonastery-1326.zip
- https://dsdarchive.com/files/demos/eviternity/44536/evit26-658.zip
- https://dsdarchive.com/files/demos/grove/12807/grov-724.zip
- https://dsdarchive.com/files/demos/planisf2/48969/planisf2os910.zip
- https://dsdarchive.com/files/demos/satchap/20510/satchap-706.zip
- https://dsdarchive.com/files/demos/sunlust/57817/sl30m2321.zip

SYSTEM SPECS:
- win11 x64
- intel i7 1260p
- 16gb ddr4 dual channel
- iris xe graphics
- 1920x1200 display, 120% scaling in windows

TIMEDEMOS TESTING METHODOLOGY:
1. clean-from-scratch cfg (only changes: vsync off, widescreen auto, demo progeessbar on)
2. autoload and sound disabled
3. each timedemo has been launched 5 times
4. between each run
5. the best and the worst results for each timedemo were excluded
6. the final score has been calculated averaging the remaining 3 results of each timedemo

PLN.WAD TESTING METHODOLOGY
1. clean-from-scratch cfg (only changes: vsync off, widescreen auto, demo progeessbar on)
2. autoload disabled, sound disabled, IDRATE cheat enabled
3. warp to the map and move to the southwest (relative to player start) corner 
4. stand still and look at the opposite (northeast) corner

**Comment by MrAlaux** [comment]
Thanks again!

**Comment by MrAlaux** [comment]
Deprecated by Woof 14.0.0 merge.
