### ISSUE TITLE
Feature requests + a bug report

### ISSUE THREAD

**Issue by El-Juancho** [MrAlaux/Nugget-Doom#50]
Can we please have an option to have the original 6 (2-7) weapon sprite in the advanced HUD?

![image](https://github.com/MrAlaux/Nugget-Doom/assets/70743149/b5fce7fa-bb33-47ed-844c-ae28624fd439)

when a weapon runs out of ammo and you have enabled the weapon atack alignement set to "centered" the the gun does not go down and draw another gun, it stays still and another gun appear instantaneously. Can we also have the "horizontal" weapon alignement option? Is the one that i use in dsda-doom and it is my fav weapon alignement option so it would be cool to have it too in nugget doom.

https://github.com/MrAlaux/Nugget-Doom/assets/70743149/c901d332-6914-4b17-876d-758f177edbb2

**Comment by MrAlaux** [comment]
> Can we please have an option to have the original 6 (2-7) weapon sprite in the advanced HUD?

A custom NUGHUD can be made for that. I'll try to write one for you in a while.

> when a weapon runs out of ammo and you have enabled the weapon atack alignement set to "centered" the the gun does not go down and draw another gun, it stays still and another gun appear instantaneously. Can we also have the "horizontal" weapon alignement option?

I'll look into these.

**Comment by MrAlaux** [comment]
Regarding the weapon numbers: download [this ZIP](https://github.com/MrAlaux/Nugget-Doom/files/12065406/nughud.zip), and extract its contents into `autoload/doom-all` in your Nugget folder.

**Comment by MrAlaux** [comment]
Forgot to mention; since this is something you're autoloading, it'll obviously stop working if the file is removed or if you prevent autoloading with the `-noautoload` command-line parameter.

**Comment by MrAlaux** [comment]
> when a weapon runs out of ammo and you have enabled the weapon atack alignement set to "centered" the the gun does not go down and draw another gun, it stays still and another gun appear instantaneously.

Fixed by b308bdb.

**Comment by MrAlaux** [comment]
> Can we also have the "horizontal" weapon alignement option? Is the one that i use in dsda-doom and it is my fav weapon alignement option so it would be cool to have it too in nugget doom.

Fixed by 792445b.
