### ISSUE TITLE
Crash when trying to open Automap

### ISSUE THREAD

**Issue by Dezaimasu** [MrAlaux/Nugget-Doom#51]
I'm not 100% sure how to reliably trigger this. I reproduced it multiple times with clean installation, but still not sure in anything bellow.
Exclusive Fullscreen is required. It's the only option I changed in fresh installation.
Most of the times it happened when I open the automap right after entering the new level.
I use this HUD (and its slightly modified version, same results) https://github.com/liPillON/nughud_fullstbar and looks like the crash is somehow related to NUGHUD.
For example this HUD https://github.com/liPillON/nughud_minimal seems working fine, so maybe the problem is with statusbar background.

Sometimes when I open the automap it looks like this screenshot, but more often the game just crashes before opening the automap. Sometimes nothing happens, but after I enter the next level it crashes when I press Tab anyway.
![nugg0000](https://github.com/MrAlaux/Nugget-Doom/assets/1636242/44345764-9ea3-42a5-bd2e-703822c0f6f9)

**Comment by MrAlaux** [comment]
Could you check if it happens when an Automap line approaches the edges of the screen? In Doom 2 Map01, try opening the Automap, disabling Follow Mode and scrolling away so the lines go beyond the screen boundaries.

Also, what OS are you using?

**Comment by Dezaimasu** [comment]
No, nothing happens in non-follow mode, scrolled all over the multiple maps. Also it looks like it crashes more often with widescreen enabled.
I'm using Win10Pro 22H2 x64, 2560x1440 screen, Nvidia driver 535.98.

**Comment by Dezaimasu** [comment]
Also sometimes it stops crashing, but no matter what the HUD always looks like that every time I open the automap. 
If from automap screen I open settings and change resolution (for example from x2 to x4) the HUD on automap screen goes back to normal and it stays that way, but looks like every time after I change resolution, it's almost guaranteed to crash on the next level on Tab press.

**Comment by Dezaimasu** [comment]
Here's what was in Event Viewer, not sure if it's helpful. Each crash is two records. I attached the content of each event, and crashdump mentioned in "Information".
![image](https://github.com/MrAlaux/Nugget-Doom/assets/1636242/22dec1c3-a99e-4e9f-b064-92f4ffc1529e)
"Error" event: [Error.txt](https://github.com/MrAlaux/Nugget-Doom/files/12063175/Error.txt)
"Information" event: [Information.txt](https://github.com/MrAlaux/Nugget-Doom/files/12063177/Information.txt)
Crashdump: [Report.txt](https://github.com/MrAlaux/Nugget-Doom/files/12063182/Report.txt)
