### ISSUE TITLE
Crashes when loading a save

### ISSUE THREAD

**Issue by kutulhu** [MrAlaux/Nugget-Doom#55]
Hello! not sure how I can send you a log, basically I was playing Zeppelin Armada (DBP59) and I would get a crash to desktop whenever reloading a save. Settings were mostly defaults except 800p rendering resolution and vanilla complevel.

I did three playthroughs of this WAD, 2 in Nugget and 1 in dsda, dsda never crashed, but it had some other bugs.

This also happened with Auger;Zenith.

This is a Windows Event Log of the hang, it's always the same, I think.

Log Name:      Application
Source:        Application Error
Date:          7/25/2023 10:08:20 AM
Event ID:      1000
Task Category: Application Crashing Events
Level:         Error
Keywords:      
User:          
Computer:      
Description:
Faulting application name: nugget-doom.exe, version: 2.0.0.0, time stamp: 0x64b09223
Faulting module name: nugget-doom.dll, version: 0.0.0.0, time stamp: 0x64b0921f
Exception code: 0xc0000005
Fault offset: 0x0000000000094c4c
Faulting process id: 0x0x25F4
Faulting application start time: 0x0x1D9BEF8E831F12F
Faulting application path: D:\Games\DOOM\Nugget Doom\nugget-doom.exe
Faulting module path: D:\Games\DOOM\Nugget Doom\nugget-doom.dll
Report Id: f6ae592b-3429-4f40-9b8d-d09aaa8900e5
Faulting package full name: 
Faulting package-relative application ID:

**Comment by MrAlaux** [comment]
Thanks for the log, but I must admit that I don't know what to do with it.

I'm actually playing through ZA myself, and it does _sometimes_ crash when reloading saves, but I've no idea of what could be the cause. I'm inclined to believe that this issue is rooted in Woof, but it really could be anything.

Does it _always_ crash for you when reloading saves?

**Comment by MrAlaux** [comment]
Potentially relevant: https://github.com/fabiangreffrath/woof/issues/1150.

**Comment by kutulhu** [comment]
> Thanks for the log, but I must admit that I don't know what to do with it.
> 
> I'm actually playing through ZA myself, and it does _sometimes_ crash when reloading saves, but I've no idea of what could be the cause. I'm inclined to believe that this issue is rooted in Woof, but it really could be anything.
> 
> Does it _always_ crash for you when reloading saves?

Certainly not always. I had the most during the last level.

**Comment by MrAlaux** [comment]
> Potentially relevant: [fabiangreffrath#1150](https://github.com/fabiangreffrath/woof/issues/1150).

It looks like this report unintentionally reopened that issue in Woof, which just got a fix. If I were to make a temporary test branch applying that fix to Nugget, could you replay some map in either WAD and see if the crashes persist?

**Comment by kutulhu** [comment]
> > Potentially relevant: [fabiangreffrath#1150](https://github.com/fabiangreffrath/woof/issues/1150).
> 
> It looks like this report unintentionally reopened that issue in Woof, which just got a fix. If I were to make a temporary test branch applying that fix to Nugget, could you replay some map in either WAD and see if the crashes persist?

Sure!

**Comment by MrAlaux** [comment]
> > If I were to make a temporary test branch applying that fix to Nugget, could you replay some map in either WAD and see if the crashes persist?
> 
> Sure!

Alright, builds are available [here](https://github.com/MrAlaux/Nugget-Doom/actions/runs/5691210354).

**Comment by kutulhu** [comment]
> > > If I were to make a temporary test branch applying that fix to Nugget, could you replay some map in either WAD and see if the crashes persist?
> > 
> > 
> > Sure!
> 
> Alright, builds are available [here](https://github.com/MrAlaux/Nugget-Doom/actions/runs/5691210354).

Did quite a bit of testing and it seems to have solved the issue.

**Comment by MrAlaux** [comment]
> Did quite a bit of testing and it seems to have solved the issue.

Good, I hope it stays like that. I'll merge the fix later alongside the rest of upstream changes, but feel free to stick to that patched build in the meanwhile.

If the crash reoccurs, please let me know. Thanks!
