### ISSUE TITLE
fast air movement when noclipping

### ISSUE THREAD

**Issue by kitchen-ace** [MrAlaux/Nugget-Doom#76]
I noticed you have inherited the bug that Crispy had for a long time until quite recently, where you get fast movement while in the air when noclipping. Here was the fix in Crispy if you want it:

https://github.com/fabiangreffrath/crispy-doom/pull/1086

**Comment by MrAlaux** [comment]
I heard about it being a bug and getting a fix, but kept it as is intentionally. I guess it's better to fix it, though.

**Comment by kitchen-ace** [comment]
I feel like a better solution might be to give the player a universal speed-boost when noclipping, maybe that can be set as an option. As long as you're aware of it though, it's up to you. It's certainly not critical.

**Comment by MrAlaux** [comment]
> I feel like a better solution might be to give the player a universal speed-boost when noclipping, maybe that can be set as an option.

Well, we already have a cheat that's literally in-game `-turbo`, we could just use that instead. What do you think?

**Comment by kitchen-ace** [comment]
Oh yeah, not familiar with all the Nugget cheats yet. Yeah that seems like it should do the trick, especially if you were able to bind it to a key like you can with noclip.

**Comment by MrAlaux** [comment]
None of Nugget's new cheats can be bound to a key, and even then, the Turbo cheat requires numeric input (just like the equivalent command-line parameter).

**Comment by kitchen-ace** [comment]
>None of Nugget's new cheats can be bound to a key

Hm, maybe they should be bindable? The ones that don't need extra input anyhow.

In any case, I really don't feel strongly about the noclip speed boost one way or another, as long as you're aware of it whatever you choose to do or not do about it is fine with me.

**Comment by MrAlaux** [comment]
Thanks for sharing Crispy's fix! That made it much easier.
