### ISSUE TITLE
[Feature Request] Widescreen translucent HUD

### ISSUE THREAD

**Issue by thekovic** [MrAlaux/Nugget-Doom#8]
Crispy Doom 5.10.3 offers this option (labeled as Screen Size 13) where the translucent HUD gets moved away from the center of the screen to fill up the widescreen space. This makes the screen look more symmetrical and leaves more room for the weapon sprite so that it doesn't get covered by numbers (most often the weapon slots). I would love to see this option added to Nugget Doom.

![image](https://user-images.githubusercontent.com/72971433/147284174-468ec9c1-8b4b-411a-b099-abb54388f63a.png)

**Comment by MrAlaux** [comment]
What a surprising coincidence; I implemented this today (210c4c2ff9aeba42e4c9cf5ad6980d40930ee136) without being aware of your request. So, well, already done, and coming up on the next release!
