### ISSUE TITLE
[Feature] smooth fake contrast?

### ISSUE THREAD

**Issue by kitchen-ace** [MrAlaux/Nugget-Doom#80]
Since you already have a switch for toggling fake contrast on or off, what would you think about implementing smooth fake contrast like in dsda or gzdoom? It's pretty subtle but I like it.

**Comment by MrAlaux** [comment]
Woof, and by consequence Nugget, already seem to have some "smooth fake contrast" allegedly from Crispy. Is this what you want?

https://github.com/MrAlaux/Nugget-Doom/blob/1e16a58b7df287cdf825e4432c882e87fd7f775d/src/p_setup.c#L1445-L1455

**Comment by MrAlaux** [comment]
Not sure what'd be some proper geometry to try it on, but here's a quick comparison:
![ezgif com-gif-maker](https://github.com/MrAlaux/Nugget-Doom/assets/73968015/93a8d54c-fcaf-494d-a95e-98858b7a2407)

EDIT: Since we already have a setting for fake contrast, I guess I can extend it to allow reverting back to the vanilla implementation. Seems that making the effect smoother means making it more aggressive.

**Comment by kitchen-ace** [comment]
Ah interesting, Crispy/Woof/Nugget's implementation is still somewhat quantized as far as the amount of light shift applied, but extends it to walls that are angled. That's good enough really. 

What DSDA does is extend the light shift level proportionally to the angle, so it's a bit smoother.

I don't notice the effect of Woof's implementation in the "usual" places that I check for fake contrast like the start of MAP01 of doom2 but in practice I doubt it will make much difference.

dsda, normal fake contrast:
![doom00](https://github.com/MrAlaux/Nugget-Doom/assets/47063032/a7257206-92ca-4dd6-a381-8c975be3852c)

dsda, smooth fake contrast:
![doom01](https://github.com/MrAlaux/Nugget-Doom/assets/47063032/e55b9994-aaa6-4a59-9480-b85f54aecc48)

woof:
![woof0000](https://github.com/MrAlaux/Nugget-Doom/assets/47063032/4f6dc4de-966a-4cb9-bf02-cc0343d194f9)

Anyhow I'm just going to close this :)

**Comment by MrAlaux** [comment]
> Ah interesting, Crispy/Woof/Nugget's implementation is still somewhat quantized as far as the amount of light shift applied, but extends it to walls that are angled. That's good enough really.

FWIW, it appears that Woof/Nugget's implementation (can't say about Crispy's) relies on the _Smooth Diminishing Lighting_ setting to some degree.

**Comment by MrAlaux** [comment]
> EDIT: Since we already have a setting for fake contrast, I guess I can extend it to allow reverting back to the vanilla implementation.

Done in https://github.com/MrAlaux/Nugget-Doom/commit/d613a9abaa50124b39ef60d3f697c57d58c86086.
