### ISSUE TITLE
View Height is not always applied instantly

### ISSUE THREAD

**Issue by Dezaimasu** [MrAlaux/Nugget-Doom#81]
When "View Height" is changed to lower value, e.g. from 41 to 38, you can instantly see the changes once you close the menu.

When it's changed to higher value nothing changes visually, and you have to restart the game/episode to see the changes.

**Comment by MrAlaux** [comment]
I'm aware of this. I believe increments in View Height are applied by simply going up a step (and maybe by performing other vertical movements).

That said, I guess I should try to make it be applied instantly.

**Comment by Dezaimasu** [comment]
It's definitely not a problem since it's not something people would change often. Just thought the behavior is weird. Thanks.

Also I have a somewhat related question if you don't mind. 
With NUGHUD, since it's only applied with the maximized viewport, the camera is kinda shifted higher.
I tried to move it lower by lowering the "View Height" so it would be on the ~same level as it is with non-maximized viewport and default "View Height" (41).

Here are two screenshots, one has default HUD and default height 41. How the game usually is.
The other has maximized viewport, NUGHUD and View Height 33.
As you can see the first blue step at the bottom of the screen is on the exact same level, but the rest of the architecture is not so much. Is there any way to achieve that effect? Put the camera in the same place where it usually is.

![DEFAULTHUD_height_41](https://github.com/MrAlaux/Nugget-Doom/assets/1636242/cecf9a38-779e-4670-b69e-27cc6f8787d0)
![NUGHUD_height_33](https://github.com/MrAlaux/Nugget-Doom/assets/1636242/46755514-3edc-4a24-84cf-0d7d6d32e07e)

**Comment by MrAlaux** [comment]
> Is there any way to achieve that effect? Put the camera in the same place where it usually is.

At least at the moment, no, there's no way to keep the original view. I might toy around with it a bit.

**Comment by MrAlaux** [comment]
Nevermind, I stand corrected: due to the way mouselook (view pitch) works, you can replicate the normal view height by looking down just a bit:

![ezgif com-gif-maker](https://github.com/MrAlaux/Nugget-Doom/assets/73968015/233e3b69-8ee1-4855-b438-7e1de23a24c2)

Admittedly, though, this is very impractical: you'd have to position your view just right every time, and somehow manage to keep it in place.

I might be able to make the mouselook "resting" height changeable through NUGHUD, as to work around the aforementioned issue.

**Comment by MrAlaux** [comment]
> I might be able to make the mouselook "resting" height changeable through NUGHUD, as to work around the aforementioned issue.

Done in https://github.com/MrAlaux/Nugget-Doom/commit/96eb18a86ef5343c63e7fd75eeb585b6f2881712.

**Comment by Dezaimasu** [comment]
I guess it might be related to the new rendering changes from Woof. 
@MrAlaux when the `nughud_viewoffset` was just added, setting it to -16 gave the exact effect from the gif you posted.
Right now this value is somewhere between 13 and 14, a bit closer to 14, so the same effect can't be achieved. It's just a few pixels difference so it's quite literally not an issue, but I thought you should know.


![nugg0009](https://github.com/MrAlaux/Nugget-Doom/assets/1636242/7f6b041c-12bf-4ef9-851a-ada5ad4625c7)

**Comment by MrAlaux** [comment]
> @MrAlaux when the `nughud_viewoffset` was just added, setting it to -16 gave the exact effect from the gif you posted.
> Right now this value is somewhere between 13 and 14, a bit closer to 14, so the same effect can't be achieved. It's just a few pixels difference so it's quite literally not an issue, but I thought you should know.

It looks like the effect of `nughud_viewoffset` is affected by FOV, which is why it worked properly on my end... with an FOV of 100 and after adjusting the math a bit. I'll look into it; thanks for the report.

**Comment by MrAlaux** [comment]
@Dezaimasu, 041a44e3c71d185b0fa31bd2c52781b25412b8d7 should have fixed it and restored compatibility with old NUGHUDs using the view offset. Could you try it, just in case?
