### ISSUE TITLE
[Feature] Compact "essentials" for WOOFHUD

### ISSUE THREAD

**Issue by NightFright2k19** [MrAlaux/Nugget-Doom#84]
This request is about adding an optional display of just the essential stats (Health, Armor, Ammo) in a single line to the WOOFHUD lump, similar to the K/I/S stats.

Explanation:
Instead of using three separate lines, it would look like this (example):
**HEL 100   ARM 100   AMM 50/50** 
(No progress bars, just the numbers.)

Reasoning:
For absolute minimalists (like me) who want to save as much screen space as possible while still being able to check the most vital stats. Also maybe for those who consider the bars kinda redundant. [Differing from my previous suggestion](https://github.com/fabiangreffrath/woof/issues/1390), this approach would not mix different HUD styles, just reorganize existing ones a bit. 

Possible realization:
- Either introduce a CVAR which toggles between the old look and the single-line mode or (probably easier)
- Add a new (optional) identifier to WOOFHUD, something like "vitals", "essentials" or "compact"

**Comment by MrAlaux** [comment]
I'm not much of a Boom HUD user myself, so I'm largely unfamiliar with it and the WOOFHUD lump. Although it should be possible to implement what you're suggesting, chances are that I won't be doing it myself.

I could mention that there's a setting to hide the "progress bars" in page 4 of the _Status Bar/HUD_ setup menu. Also, if you don't mind getting hacky about it, you could probably make an approximation of the HUD you're suggesting by using NUGHUD, but do know that it isn't as dynamic in terms of widget positioning, given that positions in it are absolute.

**Comment by MrAlaux** [comment]
Excuse me, I made a mistake. There's an alleged `hud_draw_bargraphs` CVAR which I believe disables the bars, but it isn't a Nugget-exclusive feature, and it's unrelated to the setting I mentioned previously. I must've mixed something up.

EDIT: Turns out it's a Woof feature, which should be available in that setup menu, but on a different page.

**Comment by NightFright2k19** [comment]
I see, I found it now in woof.cfg of the Woof! port. (It's also a menu option, actually.) It's something. Then it's only about placing the three stats together in one line.

**Comment by MrAlaux** [comment]
> Although it should be possible to implement what you're suggesting, chances are that I won't be doing it myself.
> [...] you could probably make an approximation of the HUD you're suggesting by using NUGHUD

Sorry, but I'll leave it at that. Maybe in the future.
