### ISSUE TITLE
[Feature] Add ZIP/PK3 support

### ISSUE THREAD

**Issue by NightFright2k19** [MrAlaux/Nugget-Doom#85]
One of the few Woof! features I'm missing here. Large wads can be compressed significantly to .zip/.pk3 format, reducing file size by up to 70%. This can make a big difference when having gathered dozens of wads on one's hard drive. Plus one could directly load files after downloading without even unpacking them.

**Comment by MrAlaux** [comment]
If Woof has the feature, Nugget should inherit it later on. As is usual, I will most likely merge changes from the next Woof release when it comes out officially.

If it's of any use, branch `upstream-merge` has some of the Woof merging work done already, but it is outdated when it comes to both the latest Woof and Nugget masters.
