### ISSUE TITLE
[Possible Bug] NUGHUD oddities

### ISSUE THREAD

**Issue by NightFright2k19** [MrAlaux/Nugget-Doom#86]
Two potential issues I have found with NUGHUD lumps:

1) When completely commenting out the _arms2_ entry (for weapon 2/pistol arms slot), the number would appear anyway, but at a completely different position. This means you are effectively unable to hide it.

Example:
```
; nughud_arms2_x 269
; nughud_arms2_y 165
; nughud_arms2_wide 1
```
--> "2" appears anyway, but elsewhere (see attached screen)
--> If lines are uncommented, "2" appears where it should

2) When using _arms1_ (for weapon 1/fists arms slot), the number remains dark while it should always be lit (like _arms2_) since it is always available. See second screenshot below.

Attachments:
![nugg0000](https://github.com/MrAlaux/Nugget-Doom/assets/54737241/c6f7904b-3e7d-446c-a011-bfa9dcf47184)
![nugg0001](https://github.com/MrAlaux/Nugget-Doom/assets/54737241/8ef36ffb-8dfa-412c-b72f-b5a45e4f5217)
[NUGHUD.txt](https://github.com/MrAlaux/Nugget-Doom/files/13987169/NUGHUD.txt)

**Comment by ak-988** [comment]
1. You can hide it by setting the arms2 x value to -1 which is the recommended way to disable certain widgets (see widgets table at https://github.com/MrAlaux/Nugget-Doom/wiki/Nugget-HUD)

2. I think that should light up when you get berserk. That's not related to the "show_berserk" cfg option which draws the berserk pack icon. I don't use the 1 digit but I'm a fan of tracking berserk mentally so maybe that option could include the HUD digit too?

**Comment by MrAlaux** [comment]
Oi, @ak-988 beat me to it. Indeed, the widgets that can be disabled in NUGHUD are disabled by setting their `x` to `-1`, and Arms number 1 is lit up only when you have Berserk.

Related to the widget disabling: omitting widget properties will simply make them fall back to their defaults, which is what's happening here. The example `nughud.lmp` -- which is identical to the default, built-in NUGHUD -- is merely included for reference; you don't necessarily have to include all those properties in whatever HUD you're making, unless you want to change them from their default values.

**Comment by NightFright2k19** [comment]
I see. That kinda makes sense, actually. Well, if it's supposed to work like that, I guess we don't really have any problem here. Thanks a lot for the fast response!
