### ISSUE TITLE
[Feature] Level Table

### ISSUE THREAD

**Issue by JohnMason1986** [MrAlaux/Nugget-Doom#87]
It can be nice to have such a feature that were previously seen in "DSDA-Doom" & "Cherry Doom", since it can improve replayability of IWADs and PWADs, because it is adding something like achievement aspect (and also competitive one, if we talking about results sharing).

Example of it:
![image](https://github.com/MrAlaux/Nugget-Doom/assets/156240806/0fd5f0a6-4f5a-4d12-8c4d-653963afae3f)

**Comment by MrAlaux** [comment]
I know about the Level Table. Although I wouldn't mind having it, I'm not interested in going through the effort of implementing it, at least at the moment.

As far as I know, Cherry Doom's codebase is always up-to-date on the latest Nugget release, so you could just stick to Cherry if you want the Level Table.
