### ISSUE TITLE
[Bug + Feature] Bugged DOOM Compatibility Settings

### ISSUE THREAD

**Issue by snekyo** [MrAlaux/Nugget-Doom#88]
### Bugged DOOM Compatibility Settings
They should become selectable after a demo ends, but sometime they just don't.
I reported this bug to the Woof team, as this issue is also in that port.

Along with fixing that bug, could you add a setting that has multiple options for disabling demos as soon as you enter the setup or general menu, or simply disabling them completely?

**Comment by MrAlaux** [comment]
> They should become selectable after a demo ends, but sometime they just don't.

If you're talking about the demos that play during the title screen, I believe that the settings would remain unavailable for as long as you don't start a new game and break out of the demo reel, since the code that disables/enables those settings is run every time a level is loaded IIRC, and all level loads during the demo reel obviously happen during demo playback.

In any case, Woof's fix for the issue should be merged when it releases its next version.

> Along with fixing that bug, could you add a setting that has multiple options for disabling demos as soon as you enter the setup or general menu, or simply disabling them completely?

This already exists: look for the "Play Internal Demos" setting in `Options > General`, in the last or penultimate page.

**Comment by snekyo** [comment]
> If you're talking about the demos that play during the title screen, I believe that the settings would remain unavailable for as long as you don't start a new game and break out of the demo reel, since the code that disables/enables those settings is run every time a level is loaded IIRC, and all level loads during the demo reel obviously happen during demo playback.

The way you said this is confusing, but from what I gather, the settings will only become available after I start a new game?

**Comment by snekyo** [comment]
Wait, no, that doesn't work
I just loaded a game and they're still blacked out.

**Comment by snekyo** [comment]
> In any case, Woof's fix for the issue should be merged when it releases its next version.

**Also:** Will Woof's patch be automatically forwarded to Nugget Doom seeing as it's built off of Woof's code, or do you mean that you will import the patch yourself when it comes out?

**Comment by MrAlaux** [comment]
> The way you said this is confusing, but from what I gather, the settings will only become available after I start a new game?

Once the first demo starts playing, yes, I believe it would be necessary to start a new game for them to become available again.

> Wait, no, that doesn't work
> I just loaded a game and they're still blacked out.

That shouldn't be the case. Have you enabled Strict Mode by any chance? That intentionally disables some settings.

If you haven't enabled Strict Mode, then there must be a bug. Could you list the exact steps to reproduce the issue?

**Comment by snekyo** [comment]
I do not have strict mode enabled. [Here's a doc of the text in my .CFG file.](https://docs.google.com/document/d/1v0w8g_UlB7H_C5fhKkbwBiI3OazTlDpxzdTANIYu8SU/edit?usp=sharing)
I simply boot the game and go into `Setup > DOOM Compatibility` to see if it works.

**Comment by MrAlaux** [comment]
> **Also:** Will Woof's patch be automatically forwarded to Nugget Doom seeing as it's built off of Woof's code, or do you mean that you will import the patch yourself when it comes out?

I'll have to merge it manually when it comes out, firstly because merges don't occur automatically and secondly because of merge conflicts. I could merge it already, but I usually only do so when official releases come out.

> I simply boot the game and go into `Setup > DOOM Compatibility` to see if it works.

FWIW, some settings in there (and in other menus) are also disabled depending on the complevel; simply put, a higher complevel means more settings available.

**Comment by snekyo** [comment]
> FWIW, some settings in there (and in other menus) are also disabled depending on the complevel; simply put, a higher complevel means more settings available.

I found the issue: I've been using the vanilla complevels all along. I just tested it and it works.
Thanks for the help.

`P.S.` When putting into the command line `-complevel vanilla`, does it automatically set the game to one of the three vanilla complevels depending on the IWAD put in? Say, if I put in the IWAD for Ultimate DOOM, and in the command line I have `-complevel vanilla`, will it set the complevel to the one made for Ultimate DOOM?

**Comment by MrAlaux** [comment]
> `P.S.` When putting into the command line `-complevel vanilla`, does it automatically set the game to one of the three vanilla complevels depending on the IWAD put in? Say, if I put in the IWAD for Ultimate DOOM, and in the command line I have `-complevel vanilla`, will it set the complevel to the one made for Ultimate DOOM?

I think that's the case, but I'm not completely sure.
