### ISSUE TITLE
Blackscreens my entire computer upon pressing windows key

### ISSUE THREAD

**Issue by kw-create** [MrAlaux/Nugget-Doom#93]
It seems like if I have the game in fullscreen, then press the windows key, no issues, but when I then renenter the game and press the windows key to exit again (both times with the game unpaused and in the latest development version that I downloaded off the Actions page), my whole screen goes black forever, and nothing fixes it except restarting the computer. Alt f4, task manager, ctrl alt delete, nothing. Please fix.

**Comment by MrAlaux** [comment]
Could you try reproducing the issue in the latest Woof release and reporting it there if it happens? This shouldn't be something that I broke myself.

This sounds like it could be related to having exclusive fullscreen enabled. Try toggling that in the meanwhile.

**Comment by kw-create** [comment]
I tried it twice on nugget, it probably would happen in woof, but I've got some important stuff open that I'll close in a little bit and then report back my findings.

**Comment by kw-create** [comment]
You were right, in exclusive full screen specifically, in woof it happens.

**Comment by MrAlaux** [comment]
In that case, could you please report the issue in Woof's repo? https://github.com/fabiangreffrath/woof/issues/new

**Comment by MrAlaux** [comment]
Relevant Woof issue: https://github.com/fabiangreffrath/woof/issues/1685.
