### ISSUE TITLE
i cant figure out where is loaded my wad

### ISSUE THREAD

**Issue by Sol1vaN** [MrAlaux/Nugget-Doom#96]
Hi there, nice sourceport.

However, I want to load a specific wad (doom ultimate) but nugget always load another wad.
i don't know what wad is, but it seems to be a wad from my steam library (example, doom 3 bfg or something).

So, its possible to make nugget portable?
I don't want any automatitation/config/search feature on this.
And if this have some that, I want to turn of all of them.

Is possible?

**Comment by MrAlaux** [comment]
I'm not entirely sure if you know about this, but I'll mention it anyways: you can pass certain parameters to Nugget through the command line or through a batch (`.bat`) file. One of the parameters is `-iwad [path]`, with which you can specify which IWAD to load.

Assuming you have `nugget-doom.exe` and whatever IWAD you're trying to load (for example, `DOOM2.WAD`) together in the same folder, and assuming that you're using Windows, you can create a `.bat` file in that same folder with the following contents...

```
nugget-doom.exe -iwad DOOM2.WAD
```

... and it should start Nugget with the Doom 2 IWAD. You can create a `.bat` by first creating a `.txt` file, editing its contents (in this case, pasting the text in the code block above) and then changing its extension to `.bat`.

Another possible option is to drag and drop IWADs on the executable, but I haven't tried that.

As far as I know, you can't disable the automatic IWAD searching, but it shouldn't matter if you're using `-iwad` or, possibly, the drag-and-drop method.

**Comment by Sol1vaN** [comment]
yep, thanks very much.
sorry, i don't mention that i'm using windows.

I've renamed the path:
`J:\Steam\steamapps\common\DOOM 3 BFG Edition\base\wads`
to
`J:\Steam\steamapps\common\DOOM 3 BFG Edition\base\wads-off`
and nugget stop automatic loading these wads.

i already know about the `-iwad [path]` parameter, but it is a little ugly implementation to use.
i prefer a config implementation, like gzdoom .ini where you can organize all your wads without making a lot of .bat or shortcuts for each wad.

for example in gzdoom:
[IWADSearch.Directories]
Path=$PROGDIR\iwads\
Path=$DOOMWADDIR
Path=$HOME

is feasible to do this in a future release?
i mean, nugget and woof use a nugget-doom.cfg/woof.cfg file where you can implement this mode.
i know that both source port (nugget-woof/gzdoom) are totally different, but is more easy to maintain a .cfg than making a different .bat/shortcuts with parameters.

however, very very nice source port.
this work flawessly, and this have a perfect aiming with vertical look mouse enabled (retro doom do this terrible).
again, thanks for the quick response.

**Comment by MrAlaux** [comment]
> is feasible to do this in a future release?

Something similar is already supported: the `DOOMWADPATH` and `DOOMWADDIR` environment variables (see [here](https://doomwiki.org/wiki/Environment_variables) for more). Changing them for your system is obviously not portable, but you might be able to create a single `.bat` that changes them temporarily (without affecting the rest of the system), for as long as the script runs (which would be until Nugget is closed).

With all of this said, there's still a problem: Nugget doesn't have an IWAD selection dialog, and instead basically loads IWADs by priority. I don't know how I could add such a dialog myself, so you'll either have to make a `.bat` that acts as one (makes you choose which IWAD to load), or you'll have to use a launcher, of which there are many.

**Comment by Sol1vaN** [comment]
thanks for the tip environment variables, is interesting way to change that, is new for me.
ps: you say 'which would be until Nugget is closed' ? Nugget will be closed?? 😮

**Comment by MrAlaux** [comment]
> ps: you say 'which would be until Nugget is closed' ? Nugget will be closed??

I meant until the application (`nugget-doom.exe` running in your machine) is closed.

**Comment by Sol1vaN** [comment]
> > ps: you say 'which would be until Nugget is closed' ? Nugget will be closed??
> 
> I meant until the application (`nugget-doom.exe` running in your machine) is closed.

aaah! 🤣🤣👍 ok thanks
