### ISSUE TITLE
Crash Logs?

### ISSUE THREAD

**Issue by BigStronk64** [MrAlaux/Nugget-Doom#99]
Is there anyway to check the logs for the runtime for the engine? It would help with modders suffering random crashes as it would allow them to see why the mod engine has crashed

**Comment by MrAlaux** [comment]
Your description is a bit too vague, at least for me. Could you give an example?

FWIW, by using `nugget-doom.com` you get a console window which displays some info. You should be able to increase verbosity from the default by tweaking the .cfg (I don't remember the exact CVAR, so search for "verbosity").

**Comment by BigStronk64** [comment]
> Your description is a bit too vague, at least for me. Could you give an example?
> 
> FWIW, by using `nugget-doom.com` you get a console window which displays some info. You should be able to increase verbosity from the default by tweaking the .cfg (I don't remember the exact CVAR, so search for "verbosity").

Say your game crashes unexpectedly, there should be a txt file outputted with the console logs

**Comment by MrAlaux** [comment]
I wouldn't know how to do that, unfortunately. The closest thing would be to run the `.com` from a terminal, or from a `.bat` with the `pause` command afterwards, so the console output remains visible once the game is closed. Then again, said output may not be very helpful, even at max verbosity.

**Comment by BigStronk64** [comment]
Understood, have a good one
